-- +goose Up
INSERT INTO exercises (name, description, user_id) VALUES
    ('Жим штанги лёжа',                'Базовое упражнение на грудь со свободным весом.',      NULL),
    ('Жим гантелей на наклонной скамье', 'Наклон 30–45°, акцент на верх груди.',               NULL),
    ('Жим штанги на наклонной вниз',   'Отрицательный наклон, акцент на низ груди.',           NULL),
    ('Разведение гантелей лёжа',       'Изолирующее движение на грудные.',                     NULL),
    ('Отжимания на брусьях',           'Наклон корпуса вперёд смещает нагрузку на грудь.',     NULL),
    ('Отжимания от пола',              'Базовое упражнение с весом тела.',                     NULL),
    ('Сведение рук в кроссовере',      'Изоляция грудных на блоках.',                          NULL),
    ('Подтягивания широким хватом',    'Базовое упражнение на широчайшие.',                    NULL),
    ('Тяга штанги в наклоне',          'Корпус около 45°, тяга к поясу.',                      NULL),
    ('Тяга верхнего блока',            'Альтернатива подтягиваниям с регулируемым весом.',     NULL),
    ('Тяга горизонтального блока',     'Акцент на среднюю часть спины.',                       NULL),
    ('Становая тяга',                  'Базовое движение на заднюю цепь.',                     NULL),
    ('Шраги со штангой',               'Изоляция трапеций.',                                   NULL),
    ('Гиперэкстензия',                 'Разгибание корпуса на тренажёре.',                     NULL),
    ('Тяга гантели одной рукой',       'Односторонняя тяга с упором в скамью.',                NULL),
    ('Жим штанги стоя',                'Армейский жим, базовое движение на плечи.',            NULL),
    ('Жим гантелей сидя',              'Жим над головой с опорой на спинку.',                  NULL),
    ('Махи гантелями в стороны',       'Изоляция средней дельты.',                             NULL),
    ('Махи гантелями в наклоне',       'Изоляция задней дельты.',                              NULL),
    ('Тяга штанги к подбородку',       'Протяжка вдоль корпуса.',                              NULL),
    ('Внешняя ротация плеча',          'Работа с вращательной манжетой.',                      NULL),
    ('Подъём штанги на бицепс',        'Базовое упражнение на бицепс.',                        NULL),
    ('Подъём гантелей «молот»',        'Нейтральный хват, акцент на плечелучевую.',            NULL),
    ('Сгибание рук на скамье Скотта',  'Изоляция с фиксацией локтей.',                         NULL),
    ('Французский жим лёжа',           'Разгибание рук из-за головы.',                         NULL),
    ('Разгибание рук на блоке',        'Изоляция трицепса стоя.',                              NULL),
    ('Отжимания узким хватом',         'Акцент на трицепс.',                                   NULL),
    ('Сгибание запястий со штангой',   'Изоляция сгибателей предплечья.',                      NULL),
    ('Разгибание запястий со штангой', 'Изоляция разгибателей предплечья.',                    NULL),
    ('Скручивания лёжа',               'Базовое упражнение на прямую мышцу живота.',           NULL),
    ('Подъём ног в висе',              'Акцент на нижнюю часть пресса.',                       NULL),
    ('Планка',                         'Статическое удержание корпуса.',                       NULL),
    ('Боковая планка',                 'Статика на косые мышцы.',                              NULL),
    ('Русский твист',                  'Ротация корпуса сидя.',                                NULL),
    ('Приседания со штангой',          'Базовое упражнение на ноги.',                          NULL),
    ('Жим ногами',                     'Жим платформы в тренажёре.',                           NULL),
    ('Выпады с гантелями',             'Шаговые выпады, акцент на ягодичные.',                 NULL),
    ('Румынская тяга',                 'Тяга на прямых ногах, акцент на бицепс бедра.',        NULL),
    ('Сгибание ног лёжа',              'Изоляция задней поверхности бедра.',                   NULL),
    ('Разгибание ног сидя',            'Изоляция квадрицепса.',                                NULL),
    ('Подъём на носки стоя',           'Икроножная в растянутом положении.',                   NULL),
    ('Подъём на носки сидя',           'Акцент на камбаловидную мышцу.',                       NULL),
    ('Отведение бедра в тренажёре',    'Изоляция средней ягодичной.',                          NULL),
    ('Сведение ног в тренажёре',       'Изоляция приводящих.',                                 NULL),
    ('Подъём носков стоя',             'Изоляция передней большеберцовой.',                    NULL),
    ('Сгибание шеи с отягощением',     'Работа с передней поверхностью шеи.',                  NULL),
    ('Разгибание шеи с отягощением',   'Работа с задней поверхностью шеи.',                    NULL)
ON CONFLICT DO NOTHING;

INSERT INTO exercise_muscles (exercise_id, muscle_group_id, role)
SELECT e.id, mg.id, v.role
FROM (VALUES
    ('Жим штанги лёжа',                'chest_middle',      'primary'),
    ('Жим штанги лёжа',                'triceps_long',      'secondary'),
    ('Жим штанги лёжа',                'delts_front',       'secondary'),
    ('Жим гантелей на наклонной скамье', 'chest_upper',     'primary'),
    ('Жим гантелей на наклонной скамье', 'delts_front',     'secondary'),
    ('Жим гантелей на наклонной скамье', 'triceps_lateral', 'secondary'),
    ('Жим штанги на наклонной вниз',   'chest_lower',       'primary'),
    ('Жим штанги на наклонной вниз',   'triceps_long',      'secondary'),
    ('Разведение гантелей лёжа',       'chest_middle',      'primary'),
    ('Разведение гантелей лёжа',       'pectoralis_minor',  'secondary'),
    ('Отжимания на брусьях',           'chest_lower',       'primary'),
    ('Отжимания на брусьях',           'triceps_long',      'secondary'),
    ('Отжимания на брусьях',           'delts_front',       'secondary'),
    ('Отжимания от пола',              'chest_middle',      'primary'),
    ('Отжимания от пола',              'triceps_lateral',   'secondary'),
    ('Отжимания от пола',              'delts_front',       'secondary'),
    ('Сведение рук в кроссовере',      'chest_middle',      'primary'),
    ('Сведение рук в кроссовере',      'serratus_anterior', 'secondary'),
    ('Подтягивания широким хватом',    'lats',              'primary'),
    ('Подтягивания широким хватом',    'biceps',            'secondary'),
    ('Подтягивания широким хватом',    'teres_major',       'secondary'),
    ('Подтягивания широким хватом',    'traps_lower',       'secondary'),
    ('Тяга штанги в наклоне',          'lats',              'primary'),
    ('Тяга штанги в наклоне',          'rhomboids',         'secondary'),
    ('Тяга штанги в наклоне',          'traps_middle',      'secondary'),
    ('Тяга штанги в наклоне',          'erector_spinae',    'secondary'),
    ('Тяга верхнего блока',            'lats',              'primary'),
    ('Тяга верхнего блока',            'biceps',            'secondary'),
    ('Тяга верхнего блока',            'teres_major',       'secondary'),
    ('Тяга горизонтального блока',     'rhomboids',         'primary'),
    ('Тяга горизонтального блока',     'lats',              'secondary'),
    ('Тяга горизонтального блока',     'traps_middle',      'secondary'),
    ('Становая тяга',                  'erector_spinae',    'primary'),
    ('Становая тяга',                  'gluteus_maximus',   'secondary'),
    ('Становая тяга',                  'biceps_femoris',    'secondary'),
    ('Становая тяга',                  'traps_upper',       'secondary'),
    ('Шраги со штангой',               'traps_upper',       'primary'),
    ('Шраги со штангой',               'traps_middle',      'secondary'),
    ('Гиперэкстензия',                 'erector_spinae',    'primary'),
    ('Гиперэкстензия',                 'gluteus_maximus',   'secondary'),
    ('Гиперэкстензия',                 'semitendinosus',    'secondary'),
    ('Тяга гантели одной рукой',       'lats',              'primary'),
    ('Тяга гантели одной рукой',       'teres_major',       'secondary'),
    ('Тяга гантели одной рукой',       'rhomboids',         'secondary'),
    ('Жим штанги стоя',                'delts_front',       'primary'),
    ('Жим штанги стоя',                'delts_side',        'secondary'),
    ('Жим штанги стоя',                'triceps_long',      'secondary'),
    ('Жим гантелей сидя',              'delts_front',       'primary'),
    ('Жим гантелей сидя',              'delts_side',        'secondary'),
    ('Жим гантелей сидя',              'triceps_medial',    'secondary'),
    ('Махи гантелями в стороны',       'delts_side',        'primary'),
    ('Махи гантелями в стороны',       'supraspinatus',     'secondary'),
    ('Махи гантелями в наклоне',       'delts_rear',        'primary'),
    ('Махи гантелями в наклоне',       'infraspinatus',     'secondary'),
    ('Махи гантелями в наклоне',       'rhomboids',         'secondary'),
    ('Тяга штанги к подбородку',       'delts_side',        'primary'),
    ('Тяга штанги к подбородку',       'traps_upper',       'secondary'),
    ('Внешняя ротация плеча',          'infraspinatus',     'primary'),
    ('Внешняя ротация плеча',          'teres_minor',       'secondary'),
    ('Внешняя ротация плеча',          'subscapularis',     'secondary'),
    ('Подъём штанги на бицепс',        'biceps',            'primary'),
    ('Подъём штанги на бицепс',        'brachialis',        'secondary'),
    ('Подъём штанги на бицепс',        'forearm_flexors',   'secondary'),
    ('Подъём гантелей «молот»',        'brachioradialis',   'primary'),
    ('Подъём гантелей «молот»',        'biceps',            'secondary'),
    ('Подъём гантелей «молот»',        'brachialis',        'secondary'),
    ('Сгибание рук на скамье Скотта',  'brachialis',        'primary'),
    ('Сгибание рук на скамье Скотта',  'biceps',            'secondary'),
    ('Французский жим лёжа',           'triceps_long',      'primary'),
    ('Французский жим лёжа',           'triceps_medial',    'secondary'),
    ('Разгибание рук на блоке',        'triceps_lateral',   'primary'),
    ('Разгибание рук на блоке',        'triceps_medial',    'secondary'),
    ('Отжимания узким хватом',         'triceps_medial',    'primary'),
    ('Отжимания узким хватом',         'chest_middle',      'secondary'),
    ('Отжимания узким хватом',         'delts_front',       'secondary'),
    ('Сгибание запястий со штангой',   'forearm_flexors',   'primary'),
    ('Разгибание запястий со штангой', 'forearm_extensors', 'primary'),
    ('Скручивания лёжа',               'rectus_abdominis',  'primary'),
    ('Скручивания лёжа',               'obliques_external', 'secondary'),
    ('Подъём ног в висе',              'rectus_abdominis',  'primary'),
    ('Подъём ног в висе',              'obliques_internal', 'secondary'),
    ('Подъём ног в висе',              'tensor_fasciae_latae', 'secondary'),
    ('Планка',                         'transverse_abdominis', 'primary'),
    ('Планка',                         'rectus_abdominis',  'secondary'),
    ('Планка',                         'quadratus_lumborum','secondary'),
    ('Боковая планка',                 'obliques_external', 'primary'),
    ('Боковая планка',                 'quadratus_lumborum','secondary'),
    ('Боковая планка',                 'obliques_internal', 'secondary'),
    ('Русский твист',                  'obliques_internal', 'primary'),
    ('Русский твист',                  'obliques_external', 'secondary'),
    ('Русский твист',                  'rectus_abdominis',  'secondary'),
    ('Приседания со штангой',          'rectus_femoris',    'primary'),
    ('Приседания со штангой',          'vastus_lateralis',  'secondary'),
    ('Приседания со штангой',          'vastus_medialis',   'secondary'),
    ('Приседания со штангой',          'gluteus_maximus',   'secondary'),
    ('Приседания со штангой',          'erector_spinae',    'secondary'),
    ('Жим ногами',                     'vastus_lateralis',  'primary'),
    ('Жим ногами',                     'rectus_femoris',    'secondary'),
    ('Жим ногами',                     'gluteus_maximus',   'secondary'),
    ('Выпады с гантелями',             'gluteus_maximus',   'primary'),
    ('Выпады с гантелями',             'rectus_femoris',    'secondary'),
    ('Выпады с гантелями',             'adductors',         'secondary'),
    ('Румынская тяга',                 'biceps_femoris',    'primary'),
    ('Румынская тяга',                 'semitendinosus',    'secondary'),
    ('Румынская тяга',                 'semimembranosus',   'secondary'),
    ('Румынская тяга',                 'gluteus_maximus',   'secondary'),
    ('Сгибание ног лёжа',              'semitendinosus',    'primary'),
    ('Сгибание ног лёжа',              'biceps_femoris',    'secondary'),
    ('Сгибание ног лёжа',              'gastrocnemius',     'secondary'),
    ('Разгибание ног сидя',            'vastus_medialis',   'primary'),
    ('Разгибание ног сидя',            'vastus_intermedius','secondary'),
    ('Разгибание ног сидя',            'rectus_femoris',    'secondary'),
    ('Подъём на носки стоя',           'gastrocnemius',     'primary'),
    ('Подъём на носки стоя',           'soleus',            'secondary'),
    ('Подъём на носки сидя',           'soleus',            'primary'),
    ('Подъём на носки сидя',           'gastrocnemius',     'secondary'),
    ('Отведение бедра в тренажёре',    'gluteus_medius',    'primary'),
    ('Отведение бедра в тренажёре',    'gluteus_minimus',   'secondary'),
    ('Отведение бедра в тренажёре',    'tensor_fasciae_latae', 'secondary'),
    ('Сведение ног в тренажёре',       'adductors',         'primary'),
    ('Подъём носков стоя',             'tibialis_anterior', 'primary'),
    ('Сгибание шеи с отягощением',     'sternocleidomastoid', 'primary'),
    ('Разгибание шеи с отягощением',   'neck_extensors',    'primary')
) AS v(exercise_name, group_code, role)
JOIN exercises e     ON e.name = v.exercise_name AND e.user_id IS NULL
JOIN muscle_groups mg ON mg.code = v.group_code
ON CONFLICT DO NOTHING;

-- +goose Down
DELETE FROM exercises WHERE user_id IS NULL;
