// СГЕНЕРИРОВАНО из миграций (muscle_regions + muscle_groups).
// Временный справочник: в API нет GET /api/v1/muscle-groups.
// Как только эндпоинт появится, client.muscleGroups() возьмёт данные оттуда,
// и этот файл останется только фолбэком.
import type { MuscleGroup } from "./types";

export const FALLBACK_MUSCLE_GROUPS: MuscleGroup[] = [
  { id: 5, code: "chest_upper", name: "Верх груди (ключичная часть)", region_code: "chest", region_name: "Грудь" },
  { id: 4, code: "chest_middle", name: "Середина груди (грудинно-рёберная часть)", region_code: "chest", region_name: "Грудь" },
  { id: 3, code: "chest_lower", name: "Низ груди (брюшная часть)", region_code: "chest", region_name: "Грудь" },
  { id: 2, code: "pectoralis_minor", name: "Малая грудная", region_code: "chest", region_name: "Грудь" },
  { id: 1, code: "serratus_anterior", name: "Передняя зубчатая", region_code: "chest", region_name: "Грудь" },
  { id: 12, code: "lats", name: "Широчайшие", region_code: "back", region_name: "Спина" },
  { id: 11, code: "traps_upper", name: "Трапеция, верх", region_code: "back", region_name: "Спина" },
  { id: 10, code: "traps_middle", name: "Трапеция, середина", region_code: "back", region_name: "Спина" },
  { id: 9, code: "traps_lower", name: "Трапеция, низ", region_code: "back", region_name: "Спина" },
  { id: 8, code: "rhomboids", name: "Ромбовидные", region_code: "back", region_name: "Спина" },
  { id: 7, code: "teres_major", name: "Большая круглая", region_code: "back", region_name: "Спина" },
  { id: 6, code: "erector_spinae", name: "Разгибатели спины", region_code: "back", region_name: "Спина" },
  { id: 19, code: "delts_front", name: "Передняя дельта", region_code: "shoulders", region_name: "Плечи" },
  { id: 18, code: "delts_side", name: "Средняя дельта", region_code: "shoulders", region_name: "Плечи" },
  { id: 17, code: "delts_rear", name: "Задняя дельта", region_code: "shoulders", region_name: "Плечи" },
  { id: 16, code: "supraspinatus", name: "Надостная", region_code: "shoulders", region_name: "Плечи" },
  { id: 15, code: "infraspinatus", name: "Подостная", region_code: "shoulders", region_name: "Плечи" },
  { id: 14, code: "teres_minor", name: "Малая круглая", region_code: "shoulders", region_name: "Плечи" },
  { id: 13, code: "subscapularis", name: "Подлопаточная", region_code: "shoulders", region_name: "Плечи" },
  { id: 27, code: "biceps", name: "Бицепс", region_code: "arms", region_name: "Руки" },
  { id: 26, code: "brachialis", name: "Брахиалис", region_code: "arms", region_name: "Руки" },
  { id: 25, code: "brachioradialis", name: "Плечелучевая", region_code: "arms", region_name: "Руки" },
  { id: 24, code: "triceps_long", name: "Трицепс, длинная головка", region_code: "arms", region_name: "Руки" },
  { id: 23, code: "triceps_lateral", name: "Трицепс, латеральная головка", region_code: "arms", region_name: "Руки" },
  { id: 22, code: "triceps_medial", name: "Трицепс, медиальная головка", region_code: "arms", region_name: "Руки" },
  { id: 21, code: "forearm_flexors", name: "Сгибатели предплечья", region_code: "arms", region_name: "Руки" },
  { id: 20, code: "forearm_extensors", name: "Разгибатели предплечья", region_code: "arms", region_name: "Руки" },
  { id: 32, code: "rectus_abdominis", name: "Прямая мышца живота", region_code: "core", region_name: "Пресс и кор" },
  { id: 31, code: "obliques_external", name: "Наружные косые", region_code: "core", region_name: "Пресс и кор" },
  { id: 30, code: "obliques_internal", name: "Внутренние косые", region_code: "core", region_name: "Пресс и кор" },
  { id: 29, code: "transverse_abdominis", name: "Поперечная мышца живота", region_code: "core", region_name: "Пресс и кор" },
  { id: 28, code: "quadratus_lumborum", name: "Квадратная мышца поясницы", region_code: "core", region_name: "Пресс и кор" },
  { id: 47, code: "rectus_femoris", name: "Прямая мышца бедра", region_code: "legs", region_name: "Ноги" },
  { id: 46, code: "vastus_lateralis", name: "Латеральная широкая", region_code: "legs", region_name: "Ноги" },
  { id: 45, code: "vastus_medialis", name: "Медиальная широкая", region_code: "legs", region_name: "Ноги" },
  { id: 44, code: "vastus_intermedius", name: "Промежуточная широкая", region_code: "legs", region_name: "Ноги" },
  { id: 43, code: "biceps_femoris", name: "Двуглавая мышца бедра", region_code: "legs", region_name: "Ноги" },
  { id: 42, code: "semitendinosus", name: "Полусухожильная", region_code: "legs", region_name: "Ноги" },
  { id: 41, code: "semimembranosus", name: "Полуперепончатая", region_code: "legs", region_name: "Ноги" },
  { id: 40, code: "gluteus_maximus", name: "Большая ягодичная", region_code: "legs", region_name: "Ноги" },
  { id: 39, code: "gluteus_medius", name: "Средняя ягодичная", region_code: "legs", region_name: "Ноги" },
  { id: 38, code: "gluteus_minimus", name: "Малая ягодичная", region_code: "legs", region_name: "Ноги" },
  { id: 37, code: "adductors", name: "Приводящие", region_code: "legs", region_name: "Ноги" },
  { id: 36, code: "tensor_fasciae_latae", name: "Напрягатель широкой фасции", region_code: "legs", region_name: "Ноги" },
  { id: 35, code: "gastrocnemius", name: "Икроножная", region_code: "legs", region_name: "Ноги" },
  { id: 34, code: "soleus", name: "Камбаловидная", region_code: "legs", region_name: "Ноги" },
  { id: 33, code: "tibialis_anterior", name: "Передняя большеберцовая", region_code: "legs", region_name: "Ноги" },
  { id: 49, code: "sternocleidomastoid", name: "Грудино-ключично-сосцевидная", region_code: "neck", region_name: "Шея" },
  { id: 48, code: "neck_extensors", name: "Разгибатели шеи", region_code: "neck", region_name: "Шея" },
];
